# This playbook update all my Proxmox PVE and PBS servers simultaneously.

- hosts: [proxmox_oli, proxmox_seb, pbs]
  name: update apt
  remote_user: root

  tasks:
  - name: apt update
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: apt upgrade
    apt:
      upgrade: dist

  - name: remove old packages and clean cache
    apt:
      autoremove: yes
      autoclean: yes
      clean: yes
